# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField()),
                ('dataArrivedTime', models.DateTimeField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('altitude', models.DecimalField(decimal_places=6, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('deviceId', models.CharField(max_length=200)),
                ('dataCalculatedTime', models.DateTimeField()),
            ],
            options={
                'db_table': 'traceper_user_was_here',
                'managed': False,
            },
        ),
    ]
