# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dataArrivedTime', models.DateTimeField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('altitude', models.DecimalField(decimal_places=6, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('deviceId', models.CharField(max_length=200)),
                ('dataCalculatedTime', models.DateTimeField()),
            ],
            options={
                'db_table': 'traceper_user_was_here',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('owner', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'traceper_campaigns',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
                ('group', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('altitude', models.DecimalField(decimal_places=6, max_digits=15)),
                ('realname', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=100)),
                ('dataArrivedTime', models.DateTimeField()),
                ('deviceId', models.CharField(max_length=200)),
                ('status_message', models.CharField(max_length=128)),
                ('status_source', models.IntegerField()),
                ('status_message_time', models.DateTimeField()),
                ('dataCalculatedTime', models.DateTimeField()),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eye_capture.Campaign')),
            ],
            options={
                'db_table': 'traceper_users',
                'managed': False,
            },
        ),
    ]
