# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye_capture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
                ('group', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('altitude', models.DecimalField(decimal_places=6, max_digits=15)),
                ('realname', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=100)),
                ('dataArrivedTime', models.DateTimeField()),
                ('deviceId', models.CharField(max_length=200)),
                ('status_message', models.CharField(max_length=128)),
                ('status_source', models.IntegerField()),
                ('status_message_time', models.DateTimeField()),
                ('dataCalculatedTime', models.DateTimeField()),
            ],
            options={
                'db_table': 'traceper_users',
                'managed': False,
            },
        ),
    ]
