# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eye_capture', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'managed': True},
        ),
    ]
