# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 17:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eye_capture', '0002_auto_20170129_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='endsAt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='campaign',
            name='startsAt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
