# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eye_capture', '0002_driver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='locationhistory',
            options={'managed': True},
        ),
    ]
