# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye_capture', '0003_auto_20170123_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('owner', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'traceper_campaigns',
                'managed': True,
            },
        ),
    ]
