# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eye_capture', '0004_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eye_capture.Campaign'),
        ),
    ]
